name: deploy_web

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'README.md'

jobs:
  deploy_web:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repo
        uses: actions/checkout@v2
      
      - name: Install flutter
        run: sudo snap install flutter --classic
      
      - name: Build for web
        run: flutter build web
        
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: cv-parser-ca402
          channelId: live
