# The only difference from the regular lint is that it lints all the codebase

name: Master Lint Code Base

on:
  pull_request:
    branches: [ master, main ]
    types: [ opened ]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
    
      - name: Install flutter
        run: sudo snap install flutter --classic
      
      - name: Fetch dependencies
        run: flutter pub get

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
